name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Perl environment
      uses: shogo82148/actions-setup-perl@v1.2.1
    - run: cd test && /./test.sh
